# Generated by Django 3.2.7 on 2021-09-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, to='form_builder.Program'),
        ),
    ]
