# Generated by Django 3.2.7 on 2021-09-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_alter_question_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_format',
            field=models.CharField(default='text field', max_length=50),
        ),
    ]
