# Generated by Django 3.2.7 on 2021-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_auto_20210921_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='question_order',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
