# Generated by Django 3.2.7 on 2021-10-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='build_date',
            field=models.CharField(default='1987', max_length=128, verbose_name='build date'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Memphis', max_length=64, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(default='38104', max_length=5, verbose_name='zip code'),
        ),
    ]
