# Generated by Django 3.2.7 on 2021-10-04 19:48

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0007_auto_20211004_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_1',
            field=models.CharField(max_length=128, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Street Address Line 2'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='build_date',
            field=models.CharField(default='1987', max_length=128, verbose_name='Home Build Date'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(default='Memphis', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=localflavor.us.models.USStateField(default='TN', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(default='38104', max_length=5, verbose_name='Zip Code'),
        ),
    ]
