# Generated by Django 3.2.7 on 2021-10-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0008_auto_20211004_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='Address',
        ),
    ]
