# Generated by Django 3.2.7 on 2021-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0012_rename_second_image_question_second_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Custom_Form',
        ),
        migrations.RemoveField(
            model_name='question',
            name='programs',
        ),
        migrations.AddField(
            model_name='question',
            name='Custom_Forms',
            field=models.ManyToManyField(blank=True, null=True, to='form_builder.Custom_Form'),
        ),
    ]
