# Generated by Django 3.2.7 on 2021-11-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0013_auto_20211025_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('what_to_expect_after_applying', models.CharField(blank=True, max_length=1000, null=True)),
                ('call', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(blank=True, max_length=500, null=True)),
                ('why_its_recommended', models.BooleanField()),
                ('eligibility_requirements', models.BooleanField()),
                ('additional_requirements', models.BooleanField()),
                ('what_you_need_to_apply', models.BooleanField()),
                ('programs', models.ManyToManyField(blank=True, null=True, to='form_builder.Program')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer_for_approval', models.CharField(blank=True, max_length=250, null=True)),
                ('statements', models.ManyToManyField(blank=True, null=True, to='form_builder.Statement')),
            ],
        ),
    ]
